//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flight_detail()
        {
            this.ticket_info = new HashSet<ticket_info>();
        }
    
        public Nullable<System.DateTime> flight_departure_date { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> available_seats { get; set; }
        public int flight_id { get; set; }
        public int flight_no { get; set; }
    
        public virtual flight flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket_info> ticket_info { get; set; }
    }
}
