//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public passenger()
        {
            this.ticket_info = new HashSet<ticket_info>();
        }
    
        public int profile_id { get; set; }
        public string password { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string address { get; set; }
        public string e_mail_id { get; set; }
        public Nullable<int> tel_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket_info> ticket_info { get; set; }
    }
}
