//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verfication
    {
        public int verify_Id { get; set; }
        public int user_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> CNIC { get; set; }
    
        public virtual userlogin userlogin { get; set; }
    }
}
