//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_Login
    {
        public int admin_Id { get; set; }
        public string admin_username { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual userlogin userlogin { get; set; }
    }
}
