//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket_info
    {
        public int ticket_id { get; set; }
        public int profile_id { get; set; }
        public int flight_id { get; set; }
        public int flight_no { get; set; }
        public string status { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual flight_detail flight_detail { get; set; }
        public virtual passenger passenger { get; set; }
    }
}
